name: Build and Push Container Images
on:
  push:
    branches: [ main ]
     
jobs: 
  build-and-push:
    permissions:
      id-token: write # Required write permission to Fetch an OIDC token
      contents: read # Read permission to access the repository contents

    runs-on: ubuntu-latest
    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          # Set required variables
          RG=$(az group list --query [].name --output tsv)
          ACR=$(az acr list --resource-group $RG --query [].name --output tsv)
          cd frontend
          az acr build --registry "$ACR" --image "frontend:${GITHUB_RUN_NUMBER}" .
          cd ../services/cart-service
          az acr build --registry "$ACR" --image "cart-service:${GITHUB_RUN_NUMBER}" .
          cd ../product-service
          az acr build --registry "$ACR" --image "product-service:${GITHUB_RUN_NUMBER}" .
